language: ruby
rvm:
  - 2.2.5
sudo: false
install: bundle install
script: jekyll build && htmlproofer ./_site --url-ignore "/#.*/" --only-4xx
git:
  depth: 3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
